import Head from 'next/head';
import Navbar from './navbar'
import styles from './layout.module.css';
// import Footer from './footer'

export default function Layout({ children }) {
    return (
        <>
            <div className={styles.container}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Navbar />
                <main>{children}</main>
                {/* <Footer /> */}
            </div>
        </>
    )
}